package teka.web.referral_modulev0.kmhfl.models;

import lombok.Data;
import teka.web.referral_modulev0.kmhfl.models.unused.*;
import teka.web.referral_modulev0.kmhfl.models.unused.FacilityContactModel;

import java.util.List;

@Data
public class FacilityModel {

    private String id;
    private String regulatory_status_name;
    private String facility_type_name;
    private String facility_type_parent;
    private String owner_name;
    private String owner_type_name;
    private String owner_type;
    private String operation_status_name;
    private String admission_status_name;
    private String county;
    private String constituency_name;
    private float average_rating;
    private List<String> facility_services;
    private List<FacilityInfrastructureModel> facility_infrastructure;
    private List<FacilityContactModel> facility_contacts;
    private List<FacilityHumanResourceModel> facility_humanresources;
    private Boolean is_approved;
    private Boolean has_edits;
    private String latest_update;
    private String regulatory_body_name;
    private String owner;
    private String date_requested;
    private String date_approved;
    private String latest_approval_or_rejection;
    private String sub_county_name;
    private String sub_county_id;
    private String county_name;
    private String constituency_id;
    private String county_id;
    private String keph_level_name;
    private String lat_long;
    private Boolean is_complete;
    private String in_complete_details;
    private String facility_checklist_document;
    private String facility_license_document;
    private String coordinates;
    private String latest_approval;
    private String county_code;
    private String constituency_code;
    private List<FacilitySpecialistModel> facility_specialists;
    private String ward_code;
    private Boolean service_catalogue_active;
    private List<FacilityUnitModel> facility_units;
    private String officer_in_charge;
    private String created;
    private String updated;
    private Boolean deleted;
    private Boolean active;
    private String search;
    private String name;
    private String official_name;
    private String code;
    private String registration_number;
    private String abbreviation;
    private String description;
    private int number_of_beds;
    private int number_of_cots;
    private int number_of_emergency_casualty_beds;
    private int number_of_icu_beds;
    private int number_of_hdu_beds;
    private int number_of_inpatient_beds;
    private int number_of_maternity_beds;
    private int number_of_isolation_beds;
    private int number_of_pharmacy_drugs;
    private int number_of_diagnostic_equipment;
    private int number_of_theatres;
    private int number_of_consultation_rooms;
    private int number_of_wards;
    private int number_of_outpatient_departments;
    private int number_of_laboratories;
    private int number_of_radiology_rooms;
    private int number_of_physiotherapy_rooms;
    private int number_of_maternity_rooms;
    private int number_of_labor_rooms;
    private int number_of_delivery_rooms;
    private int number_of_pharmacy_units;
    private int number_of_surgical_theatres;
    private int number_of_hd_units;
    private int number_of_ventilators;
}
